# Generated by Django 5.2.5 on 2025-09-01 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='booking_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='student_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='tutor_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='student_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='tutor_id',
            field=models.UUIDField(),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['tutor_id'], name='ratings_tutor_i_918088_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['student_id'], name='ratings_student_66bfdd_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['booking_id'], name='ratings_booking_a5123e_idx'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('booking_id', 'student_id'), name='uniq_rating_per_booking_student'),
        ),
        migrations.AlterModelTable(
            name='rating',
            table='ratings',
        ),
    ]
