# Generated by Django 5.2.5 on 2025-08-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_rating_booking_id_alter_complaint_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='booking_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='student_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='tutor_id',
            field=models.UUIDField(),
        ),
    ]
